version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    ports:
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
    environment:
      - SERVICES=serverless,cognito,rds,sns,cloudformation,sts,redshift
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB=8080
      #- PERSISTENCE=${PERSISTENCE-}
      #- LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      #- LOCALSTACK_HOSTNAME=|
    volumes:
      - "${TMPDIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    env_file:
      - .env